---

- name: packages required for ansible mysql modules are present
  apt: name="{{ packages }}" state=present
  vars:
    packages:
     - python3-dev
     - libmysqlclient-dev

- name: python package manager is present
  apt: name=python3-pip state=present

- name: python package required for ansible MySQL modules is present
  pip: name=mysqlclient

- name: create databases
  mysql_db:
    name: "{{ item }}"
    collation: "{{ db_collation }}"
    state: present
  with_items: "{{ percona_databases }}"
  when: percona_databases is defined

- name: create users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(lookup('password', [percona_local_passdb, '/', inventory_hostname, '/', 'percona.', item.name, ' chars={{ percona_pass_complexity }} length={{ percona_pass_len }}']|join)) }}"
    host: "{{ item.host }}"
    priv: "{{ item.database }}.*:ALL"
    state: present
  with_items: "{{ percona_users }}"
  when: percona_users is defined
