---

- name: packages required for ansible mysql modules are present
  apt:
    pkg: python3-pymysql
    state: present
  when: percona_users is defined or percona_databases is defined

- name: create databases
  mysql_db:
    login_unix_socket: /run/mysqld/mysqld.sock
    name: "{{ item }}"
    collation: "{{ db_collation }}"
    state: present
  with_items: "{{ percona_databases }}"
  when: percona_databases is defined

- name: create users
  mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    name: "{{ item.name }}"
    password: "{{ item.password | default(lookup('password', [percona_local_passdb, '/', inventory_hostname, '/', 'percona.', item.name, ' chars={{ percona_pass_complexity }} length={{ percona_pass_len }}']|join)) }}"
    host: "{{ item.host }}"
    priv: "{{ item.database }}.*:ALL"
    state: present
  with_items: "{{ percona_users }}"
  when: percona_users is defined
  no_log: true
