---

- name: percona debconf settings
  debconf:
    name: "percona-server-server-{{ percona_version }}"
    question: "{{ item.question }}"
    value: "{{ percona_root_password }}"
    vtype: "password"
  with_items:
   - { question: 'percona-server-server/root_password' }
   - { question: 'percona-server-server/root_password_again' }

- name: percona is installed
  apt:
    pkg:
     - "percona-server-server-{{ percona_version }}"
     - "percona-server-client-{{ percona_version }}"
    state: present

- name: percona is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: ensure config is present
  copy:
    src: "{{ item }}.cnf"
    dest: "/etc/mysql/conf.d/{{ item }}.cnf"
  with_items:
   - client
   - mysqld
   - mysqldump
  notify:
   - restart mysql
